name: CI for run UI tests and save report to gh-pages.

on:
  push:
  pull_request:

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Install and exec tests
        run: npm ci && npm run test

      - name: Get allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history/allure-history
          keep_reports: 5

      - name: Deploy report to Github Pages
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          access_token: ${{ github.token }}
          branch: gh-pages
          folder: allure-history/allure-history
